package org.eth.demo.gendomain;

import javax.annotation.Generated;

/** Defines the global names of the domain model and domain model fields.
* This shall be used as a static overall domain model names reference within SEB Server Web-Service as well as within the integrated GUI
* This file is generated by the org.eth.demo.sebserver.gen.DomainModelNameReferencePlugin and must not be edited manually.**/
@Generated(value="org.mybatis.generator.api.MyBatisGenerator",comments="org.eth.demo.sebserver.gen.DomainModelNameReferencePlugin",date="2018-11-01T16:16:54.726+01:00")
interface Domain {

    interface ConfigurationAttribute {
        String ENITIY_NAME = "ConfigurationAttribute";
    }

    interface ConfigurationValue {
        String ENITIY_NAME = "ConfigurationValue";
    }

    interface Orientation {
        String ENITIY_NAME = "Orientation";
    }

    interface Configuration {
        String ENITIY_NAME = "Configuration";
    }

    interface ConfigurationNode {
        String ENITIY_NAME = "ConfigurationNode";
    }

    interface ExamConfigurationMap {
        String ENITIY_NAME = "ExamConfigurationMap";
    }

    interface Exam {
        String ENITIY_NAME = "Exam";
    }

    interface ClientConnection {
        String ENITIY_NAME = "ClientConnection";
    }

    interface ClientEvent {
        String ENITIY_NAME = "ClientEvent";
    }

    interface Indicator {
        String ENITIY_NAME = "Indicator";
    }

    interface Institution {
        String ENITIY_NAME = "Institution";
    }

    interface SebLmsSetup {
        String ENITIY_NAME = "SebLmsSetup";
    }

    interface User {
        String ENITIY_NAME = "User";
    }

    interface UserRole {
        String ENITIY_NAME = "UserRole";
    }
}